celery:
  CELERY_BROKER_URL: "redis://redis:6379"
  CELERY_RESULT_BACKEND: "redis://redis:6379"
  CELERY_TRACK_STARTED: True
  CELERY_SEND_EVENTS: True

hub_db:
  engine: postgresql+psycopg2
  host: db
  port: 5432
  user: master
  password: password
  database: fulcrum
# !TODO sensitive data needs to be moved to environment variables
